language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
env:
  global:
    secure: q05jF68MP+pNV+9yOzdGpgj66g/CG0rYPDDOWUiy7myEbsyHC+pyJ/oabAKO95uJ6PbS3qVJafsFKbzYx3gEIPYNzXubqDssTInV0r2YxeYdgF/Q2nP0PD3h0kePM2y1AmT1HKqBQD9BP2zlO6wjg4uGvYu6LhW7DpY1zqdfwuQVXLwzAXZrb3i7JUBZ0XTHvYVoyb9lQfDAOERgdJurtqROo+cztosGTGRlrWU6xWq6inOhISQ6K+AMpQHbDej6shqtzKqX5rIGq+56+D6REmiGGWmQcjF3sOxK/Bf/lzE+Lgs1cd3xBbidWccScWokmGDEzJqBmH2DpJHMlAEUiK5KJ3GH834Jl1g3rWe1FAv79bKUHDBGG5pHKiCVvSJzdn6Tnb+XmxaI1SRSAv7/79RrImNvh9RegkFggQcYUNe1vRBrnvYcHSU1RhdkSaMzE1NqtIL8ukyluHHnZysof0WxVY4hJb/ndObl5EXDfLP8gRV2InYbEmhBV2l72nuHR6yfqLcDhHpCPXlZr+44Z7nUyfliPCtQ72s4YxOQPeV22TCmCmKaKI5bH4qpg0PdqWDQ4r+jTiRHAGWgoNrXPwpYKcGdvsVxEC6U2mjN8I1KBYBVIlLS8kwGTsBIupfcBWEBLheI3HmeGhAmm7kxBZTAV944boZuhgwN4K88DE8=
